[package]
name = "solforge-case-study"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.4", features = ["derive"] }
thiserror = "1.0"
tokio = { version = "1.34", features = ["full"] }
url = "2.5.2"
